### ISSUE TITLE
"Could not find file 'C:\Users\xxxx\Downloads\Release\LH_Config_In.json"

### ISSUE THREAD

**Issue by mistathugisolation** [sencercoltu/steamvr-undistort#15]
Upon running as admin I get
"Could not find file 'C:\Users\xxxx\Downloads\Release\LH_Config_In.json"

Is this searching for a particular file I need to drop into the directory?

HMD is Vive Cosmos

**Comment by mistathugisolation** [comment]
Debug output:

`Exception: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
Exception: System.UnhandledExceptionEventArgs    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at Undistort.Program.LoadLHSettings(String ovrPath)
   at Undistort.Program.Main() 
`

**Comment by mistathugisolation** [comment]
I think this may have something to do with me being unable to open lighthouse_console manually, it just starts and then closes immediately. I ran it via windows CMD to see what it was doing, returns with the error:

Version:  lighthouse_console.exe (buildbot_vortex-windows_steamvr_rel_hotfix_win64@vortex-windows)  05873166
Attached lighthouse receiver devices: 3
No connected lighthouse device found.

**Comment by sencercoltu** [comment]
Is there another tool for the cosmos to dump/upload the distortion profile?

**Comment by mistathugisolation** [comment]
> Is there another tool for the cosmos to dump/upload the distortion profile?

Not AFAIK. I'm digging around the directories to try and find something atm.

Will also try get a hold of an elite profile as that would obviously be the closest, same stock lenses.

**Comment by PrzemChuck** [comment]
> > Is there another tool for the cosmos to dump/upload the distortion profile?
> 
> Not AFAIK. I'm digging around the directories to try and find something atm.
> 
> Will also try get a hold of an elite profile as that would obviously be the closest, same stock lenses.

Did you find any solutions?
