### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by nwWNTR** [sencercoltu/steamvr-undistort#7]
I keep getting the above error when starting the program.

Log file:

Exception: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
Exception: System.UnhandledExceptionEventArgs    at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Undistort.Program.LoadLHSettings(String ovrPath)
   at Undistort.Program.Main()

**Comment by nwWNTR** [comment]
I think it had to do with the vive wands. I turned both of them off, leaving just the headset powered on, and now it works.
