### ISSUE TITLE
launch error

### ISSUE THREAD

**Issue by QUAKEULUS** [sencercoltu/steamvr-undistort#8]
---------------------------

---------------------------
Specified argument was out of the range of valid values.

Parameter name: count
---------------------------
OK   
---------------------------

**Comment by QUAKEULUS** [comment]
debug.log

Exception: System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs
Exception: System.UnhandledExceptionEventArgs    at System.Linq.Enumerable.Range(Int32 start, Int32 count)
   at FastJsonLib.FastJson.Prettify(String str)
   at Undistort.Program.LoadLHSettings(String ovrPath)
   at Undistort.Program.Main()
